### PR TITLE
Setup docs out-of-date

### PR DESCRIPTION
**Pull request by patcon**
Seems the CLI (including migrate) are now elsewhere:
https://github.com/sequelize/sequelize/blob/master/changelog.md#200-rc4

I'll submit a PR when I'm orientated

### CODE REVIEW

**Comment by xdarklight** [comment]
Indeed, same problem (probably) with the updates (migration steps).
Tell me whenever I can help out!

**Comment by patcon** [comment]
Not ready for merge yet, fyi

**Comment by patcon** [comment]
FYI
- Chef Cookbook: https://github.com/mission-impossible-android/chef-cm-update-server
- Demo VM: https://github.com/mission-impossible-android/cm-update-server-vagrant

EDIT: they both still need work, but at least minimally useful for someone else now :)

**Comment by patcon** [comment]
Anyhow, I guess this is good to merge if it looks ok

**Comment by xdarklight** [comment]
I have commented d1db75e - but apart from that it looks fine

**Pull request merged**
